name: build

on:
  push:
    branches: [main]
    paths:
      - .github/**
      - src/**
      - test/**
      - Makefile
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies on Linux
        if: matrix.os == 'ubuntu-20.04'
        run: sudo apt-get install -y sqlite3 gcc unzip

      - name: Install dependencies on Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          choco install -y mingw
          choco install -y unzip
          choco install -y sqlite

      - name: Install dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: brew install sqlite3 gcc unzip

      - name: Download and prepare sources
        run: |
          make prepare-dist
          make download-sqlite

      - name: Compile and test on Linux
        if: matrix.os == 'ubuntu-20.04'
        run: |
          make compile-linux
          make test-all

      - name: Compile on Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          make compile-windows
          make test-all

      - name: Compile on macOS
        if: matrix.os == 'macos-latest'
        run: |
          make compile-macos
